spring:
  datasource: 
    username: root 
    password: root 
    url: jdbc:mysql://localhost:3306/empDB2
    driver-class-name: com.mysql.cj.jdbc.Driver

#data jpa spec

  jpa: 
    hibernate: #it will create the table and display and show all that is happening with the sql db
      ddl-auto: update
      show-sql: true